# Train/val/test sets as 
# 1) dir: path/to/imgs, 
# 2) file: path/to/imgs.txt, or 
# 3) list: [path/to/imgs1, path/to/imgs2, ..]
#TODO: adjust the filepaths
path: ../dataset  # dataset root dir
train: images  # train images (relative to 'path')
val: images  # val images (relative to 'path')
test: images # test images (optional)

# Classes
names:
  0: irrelevant
  1: relevant